import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'module';

const banner = `/*
This file is generated by esbuild. Read the source at
https://github.com/ronamosa/uncommon-terminal
*/
`;

const production = process.argv[2] === 'production';

const context = await esbuild.context({
    banner: { js: banner },
    entryPoints: ['src/main.ts'],
    bundle: true,
    external: ['obsidian', 'electron', ...builtinModules],
    format: 'cjs',
    target: 'es2022',
    logLevel: 'info',
    // pty_helper.py rides along as a string so the plugin can write it out.
    loader: { '.py': 'text' },
    sourcemap: production ? false : 'inline',
    treeShaking: true,
    outfile: 'main.js',
    minify: production,
});

if (production) {
    await context.rebuild();
    await context.dispose();
} else {
    await context.watch();
}
