import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

esbuild.build({
    banner: { js: banner },
    entryPoints: ['main.ts'],
    bundle: true,
    external: [
        'obsidian',
        'electron',
        'node-pty-prebuilt-multiarch', // native addon – loaded at runtime via require()
        ...builtinModules,
    ],
    format: 'cjs',
    target: 'es2022',
    logLevel: 'info',
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    outfile: 'main.js',
    minify: prod,
}).catch(() => process.exit(1));